osx_image: xcode8
dist: trusty

language: node_js
node_js: node

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - icnsutils

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

install:
- npm install electron-builder # force install next version to test electron-builder
- npm install
- npm prune

script:
- npm run release

branches:
  only:
    - v3