language: node_js
node_js: node

os:
  - linux
  - osx
dist: trusty
sudo: required

env:
  npm_config_target: '$(npm show electron version)'
  npm_config_arch: x64
  npm_config_target_arch: x64
  npm_config_disturl: https://atom.io/download/atom-shell
  npm_config_runtime: electron
  npm_config_build_from_source: true

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

before_install:
  - env
  - openssl aes-256-cbc -K $encrypted_9f35b7f09ebe_key -iv $encrypted_9f35b7f09ebe_iv -in ssh-key.enc -out $HOME/.ssh/id_ecdsa -d
  - chmod 600 $HOME/.ssh/id_ecdsa

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p bin; curl --location --retry 5 https://github.com/aria2/aria2/releases/download/release-1.29.0/aria2-1.29.0-osx-darwin.tar.bz2 | tar --strip-components=2 -C bin -jxf - aria2-1.27.1/bin/aria2c; fi
  - npm install
  - npm prune

script:
  - npm run dist

deploy:
  provider: script
  script: curl --fail --verbose --request POST "https://wudizhanche.mycard.moe/publish?platform=${TRAVIS_OS_NAME}&version=${TRAVIS_TAG}"
  on:
    tags: true