language: node_js
node_js: node

os:
  - linux
  - osx
dist: trusty
sudo: required

env:
  npm_config_target: 1.4.5
  npm_config_arch: x64
  npm_config_target_arch: x64
  npm_config_disturl: https://atom.io/download/atom-shell
  npm_config_runtime: electron
  npm_config_build_from_source: true

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

before_install:
  - openssl aes-256-cbc -K $encrypted_9f35b7f09ebe_key -iv $encrypted_9f35b7f09ebe_iv -in ssh-key.enc -out $HOME/.ssh/id_ecdsa -d
  - chmod 600 $HOME/.ssh/id_ecdsa

install:
- npm install
- npm prune

script:
- npm run dist

deploy:
  provider: script
  script: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scp dist/mac/MyCard-$TRAVIS_TAG.dmg dist/mac/MyCard-$TRAVIS_TAG-mac.zip root@wudizhanche.mycard.moe; else ls -r; fi
  on:
    tags: true