version: '{build}'

platform: x86

environment:
  npm_config_target: 1.2.3
  npm_config_arch: ia32
  npm_config_target_arch: ia32
  npm_config_disturl: https://atom.io/download/atom-shell
  npm_config_runtime: electron
  npm_config_build_from_source: true

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

shallow_clone: true

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node # 6 $env:platform
  #- git reset --hard HEAD
  - npm install npm -g
  - npm install electron-builder
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run dist
  - tree /f dist

#artifacts:
#  - path: ygopro-images
#    name: ygopro-images-$(locale)
#    type: zip
#  - path: records-$(locale).json
#    name: records-$(locale)
#
#deploy:
#  provider: FTP
#  protocol: sftp
#  host: pokeboy.mycard.moe
#  username: root
#  folder: /data/publish

test: off