version: '{build}'

platform: x86

environment:
  priv_key:
      secure: ek1AH0N8/KF6VoildmkHnu4TY1yBZcptm20AesAOanRSSGLFqkXeRxL80mHSXtiVY8ggtQNsEQR4M69gCiw1OPVWz4OAN6Vg6id6kho9GqYxWCdADbmffSNPB5leksRGjGmkAF99WHiOIZrLRUb6Bia91Fe5+SngPhI01GDDUZA2urv9x50uBBhc+kvV0bv7J5TeXDGr7tfZ3J2aL/3tf/WPqBkqjWlGAj99HTWpkIiQgwaBHoyBvEFD0uHa1BdSmI7PySGabbx4/4zqyGkO38Ce7t/Ntu/dgedzVxlXYfuiXDI8caAPZSVsJ9E2S3VKesZJzHtV9KM/8Xq0RFPythdC/qTvd2e3IAZGudZpgbUHGAHLJnCzn189Zm+Qle8CbbVuPNDcf1B/G/XwEU2MsDXGkF/kFxdeqbHgjzneyns=
  BT_TOKEN:
      secure: VNRwtuHDHJQS0UbCW2WmNSyyRtKhYPC5FCZztllsIygyg3dj5H/YY89UUmPW9vU7
  GH_TOKEN:
      secure: itZ9Z1dxEpfPJLdTs/PiY98pVZ3GCLNWfid7eAu7SL88Jl9AIrf/3rviKFEbsnoY
  npm_config_target: 1.4.5
  npm_config_arch: ia32
  npm_config_target_arch: ia32
  npm_config_disturl: https://atom.io/download/atom-shell
  npm_config_runtime: electron
  npm_config_build_from_source: true

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

shallow_clone: true

init:
  - ps: $fileContent = "-----BEGIN EC PRIVATE KEY-----`n"
  - ps: $fileContent += $env:priv_key.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END EC PRIVATE KEY-----`n"
  - ps: Set-Content c:\users\appveyor\.ssh\id_ecdsa $fileContent
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node # 6 $env:platform
  #- git reset --hard HEAD
  - npm install npm -g
  - npm install electron-builder
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run dist

test: off

artifacts:
  - path: dist/MyCard Setup $(APPVEYOR_REPO_TAG_NAME).exe
  - path: dist/latest.yml

deploy:
  - provider: FTP
    protocol: sftp
    host:
      secure: kOmWSMPWqwRatoWbsDnyEePCfTVRsmKqvCTREDvihT8=
    username:
      secure: K5zchLMnJ3JaEqx3/bSl5A==
    password:
      secure: Eu+oVcSuxpc6BVmjxSgM2yBCRnwRsoUye8QCkaIGlX4=
    folder:
      secure: I/l1mtYuzA7y/ujuCXCahQ==
    on:
      appveyor_repo_tag: true